backend:
  name: git-gateway
  branch: main          # o “master” se il tuo branch principale si chiama così

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "products"
    label: "Prodotti"
    files:
      - label: "Elenco Prodotti"
        name: "products"
        file: "data/products.json"
        fields:
          - label: "Prodotti"
            name: "products"
            widget: "list"
            types:
              - label: "Singolo prodotto"
                name: "product"
                widget: "object"
                fields:
                  - { label: "Titolo",       name: "title",       widget: "string" }
                  - { label: "Descrizione",  name: "description", widget: "text" }
                  - { label: "Prezzo",       name: "price",       widget: "number" }
                  - { label: "Categoria",    name: "category",    widget: "select", options: ["acrylic","ai"] }
                  - { label: "Immagine",     name: "image",       widget: "image" }