backend:
  name: git-gateway
  branch: main        # o il ramo principale del tuo repo

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "gallery"
    label: "Gallery"
    folder: "data"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    fields:
      - { label: "ID",           name: "id",          widget: "string" }
      - { label: "Title",        name: "title",       widget: "string" }
      - { label: "Description",  name: "description", widget: "text" }
      - { label: "Category",     name: "category",    widget: "select", options: ["acrylic", "ai"] }
      - { label: "Image",        name: "image",       widget: "image" }
