backend:
  name: git-gateway
  branch: main

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "products"
    label: "Products"
    files:
      - label: "Products List"
        name: "products"
        file: "data/products.json"
        fields:
          - label: "Products"
            name: "products"
            widget: "list"
            types:
              - label: "Single Product"
                name: "product"
                widget: "object"
                fields:
                  - { label: "Title",       name: "title",       widget: "string" }
                  - { label: "Description", name: "description", widget: "text" }
                  - { label: "Price",       name: "price",       widget: "number" }
                  - { label: "Category",    name: "category",    widget: "select", options: ["acrylic","ai"] }
                  - { label: "Image",       name: "image",       widget: "image" }
